name: Build

on:
  push:
    branches:
      - master
      - release/0.0.8
  repository_dispatch:
    types: [publish-app]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Setup Node.js (${{ matrix.node_version }})
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - run: npm install
      - run: npm run build:android-release
      # - name: Variables
      #   run: |
      #     echo VERSION=$(npm run version --silent) >> $GITHUB_ENV
      #   shell: bash
